### ISSUE TITLE
Update game data

### ISSUE THREAD

**Issue by TomClancyIsDead** [larzm42/dom4inspector#6]
Hi! Patch 4.25 is out. How does one go about updating the game data? I'd like to be able to do it on my local copy and would be happy to issue pull requests for it as well if you'd like.

**Comment by larzm42** [comment]
I went ahead and updated the game data. It's a bit of a manual process but here is how it is done:
- Get project dominions-tools and dom4utils
- In dominions-tools the python scripts need to be updated with the new base addresses of the objects in the executable. I do this by looking at the old version and new version and finding the proper offsets. Usually there is a string in the executable to tie the address to.
- Run the dominons-data-tool script
- This creates a sql lite database containing the csv files from the inspector related to weapons, armor, spells and nations
- Export the tables that match the ones in the inspector as csv files
- Now load up the dom4utils project and update the offsets in the Starts.java file to the new offsets (same process as before)
- Run the Dom4Utils.java class. This will create spreadsheets containing the new data for units, items, sites mercenaries and events.
- Copy these into the files in the inspector.

I'm sure I missed some steps but this is roughly how its done.
